name = "Render"
uuid = "71b1e054-9cd0-11e8-2177-cd30085e35eb"
authors = ["Jeffrey Lin <jeffrey@icurse.nl>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FilePaths = "8fc22ac5-c921-52a6-82fd-178b2807b824"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Tokenize = "0796e94c-ce3b-5d07-9a54-7f471281c624"
